# Generated by Django 4.2.20 on 2025-05-09 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_alter_address_address_type'),
        ('cart', '0002_order_address_order_shipping_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addresses.address'),
        ),
    ]
