# Generated by Django 4.2.20 on 2025-04-24 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_alter_address_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={},
        ),
    ]
