# Generated by Django 4.2.20 on 2025-05-09 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_alter_address_address_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
    ]
