# Generated by Django 4.2.20 on 2025-05-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondaryimage',
            name='image',
            field=models.ImageField(upload_to='secondary'),
        ),
    ]
