# Generated by Django 4.2.20 on 2025-04-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(default='', max_length=30)),
                ('address', models.CharField(default='', max_length=50)),
                ('phone_number', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
